services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  mysql:
    extends:
      file: mysql/docker-compose-mysql.yaml
      service: mysql

volumes:
  mysql-data: